name: Build, Pack and push to Nuget repository

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Create the Package
      run: dotnet pack --configuration Release

    - name: Publish
      run: dotnet nuget push "./Cpnucleo.Shared/bin/Release/Cpnucleo.Shared.1.0.0-preview.1.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json