name: Build, Pack and Push to NuGet repository

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./src/Cpnucleo.Shared"

    steps:
    - uses: actions/checkout@main

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Install dependencies
      run: dotnet restore        

    - name: Generate build number
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}  

    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
      # Or, if you're on Windows: echo "Build number is ${env:BUILD_NUMBER}"     

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Create NuGet package
      run: dotnet pack --configuration Release --no-restore

    - name: Publish
      run: dotnet nuget push "bin/Release/Cpnucleo.Shared.1.0.1.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
