name: Build, Pack and push to NuGet repository

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./src/Cpnucleo.Shared"

    steps:
    - uses: actions/checkout@main

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Install dependencies
      run: dotnet restore        

    - name: Build project
      run: dotnet build --configuration Release --no-restore -p:Version=1.0.0-preview.1

    - name: Create NuGet package
      run: dotnet pack --configuration Release

    - name: Publish
      run: dotnet nuget push "bin/Release/Cpnucleo.Shared.1.0.0-preview.1.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
